import { Task, Routine, ReturnDay, HelpfulInsight, UserSettings, Reset, WellnessJournalEntry } from '../types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Work on project',
    category: 'productive',
    icon: '💻',
    timeCategory: 'now',
    scheduledTime: undefined,
    durationMinutes: 25,
    priority: 'must',
    minimum: 'Open laptop and open the file',
    normal: 'Work focused for 25 minutes',
    extra: 'Review and commit current changes',
    steps: [
      { id: 's1', title: 'Sit down at the workspace', completed: true },
      { id: 's2', title: 'Open laptop lid', completed: false, isMinimum: true },
      { id: 's3', title: 'Open the project file', completed: false },
      { id: 's4', title: 'Review the last line edited', completed: false },
      { id: 's5', title: 'Make one small edit or test run', completed: false },
    ],
    companyPreference: 'someone_nearby',
    completed: false,
    orderIndex: 0,
  },
  {
    id: 'task-2',
    title: 'Listen to quiet music & breathe',
    category: 'rest',
    icon: '☕',
    timeCategory: 'today',
    scheduledTime: '15:30',
    durationMinutes: 15,
    priority: 'should',
    minimum: 'Sit with eyes closed for 2 minutes',
    normal: 'Enjoy 15 minutes of calm audio',
    extra: 'Make a warm cup of herbal tea',
    steps: [
      { id: 'r1', title: 'Put on headphones', completed: false },
      { id: 'r2', title: 'Press play on ambient playlist', completed: false },
      { id: 'r3', title: 'Rest head back and exhale', completed: false },
    ],
    companyPreference: 'alone',
    completed: false,
    orderIndex: 1,
  },
  {
    id: 'task-3',
    title: 'Eat a proper lunch',
    category: 'wellness',
    icon: '🍳',
    timeCategory: 'today',
    scheduledTime: '13:00',
    durationMinutes: 20,
    priority: 'must',
    minimum: 'Grab a piece of fruit or toast',
    normal: 'Sit down with a warm meal',
    extra: 'Drink a full tall glass of water with it',
    steps: [
      { id: 'l1', title: 'Walk to the kitchen', completed: false },
      { id: 'l2', title: 'Get food onto a plate', completed: false },
      { id: 'l3', title: 'Eat without rushing', completed: false },
    ],
    companyPreference: 'no_preference',
    completed: false,
    orderIndex: 2,
  },
  {
    id: 'task-4',
    title: 'Reset desk surface',
    category: 'routine',
    icon: '🧹',
    timeCategory: 'later',
    durationMinutes: 10,
    priority: 'could',
    minimum: 'Put 1 empty cup in the kitchen sink',
    normal: 'Throw away wrappers & tuck papers',
    extra: 'Wipe surface with a damp cloth',
    steps: [
      { id: 'd1', title: 'Take cups to sink', completed: false },
      { id: 'd2', title: 'Throw scrap paper away', completed: false },
      { id: 'd3', title: 'Line up keyboard and mouse', completed: false },
    ],
    companyPreference: 'background_company',
    completed: false,
    orderIndex: 3,
  },
  {
    id: 'task-5',
    title: 'Shower & get dressed',
    category: 'wellness',
    icon: '🚿',
    timeCategory: 'today',
    scheduledTime: '09:00',
    durationMinutes: 15,
    priority: 'must',
    minimum: '2-minute warm rinse',
    normal: 'Full warm shower',
    extra: 'Take time to wash hair if needed',
    steps: [
      { id: 'sh1', title: 'Turn water on warm', completed: true },
      { id: 'sh2', title: 'Step in for rinse', completed: true },
    ],
    companyPreference: 'alone',
    completed: true,
    completedAt: '2026-09-19T09:18:00',
    completedTier: 'minimum',
    orderIndex: 4,
  },
  {
    id: 'task-6',
    title: 'Morning glass of water',
    category: 'wellness',
    icon: '💧',
    timeCategory: 'today',
    durationMinutes: 2,
    priority: 'should',
    minimum: 'Take three sips',
    normal: 'Drink full glass',
    steps: [
      { id: 'w1', title: 'Fill glass', completed: true },
      { id: 'w2', title: 'Drink slowly', completed: true },
    ],
    companyPreference: 'no_preference',
    completed: true,
    completedAt: '2026-09-19T08:30:00',
    completedTier: 'normal',
    orderIndex: 5,
  },
];

export const WELLNESS_TASK_PRESETS = [
  // Must
  { title: 'Brush teeth', icon: '🪥', priority: 'must' as const, minimum: 'Rinse with water', normal: 'Full brush — 2 minutes', category: 'wellness' as const, durationMinutes: 3 },
  { title: 'Wash face', icon: '🧼', priority: 'must' as const, minimum: 'Splash cold water on face', normal: 'Gentle cleanse and rinse', category: 'wellness' as const, durationMinutes: 4 },
  { title: 'Take medication', icon: '💊', priority: 'must' as const, minimum: 'Take with any amount of water', normal: 'Take with full glass of water', category: 'wellness' as const, durationMinutes: 2 },
  { title: 'Drink water', icon: '💧', priority: 'must' as const, minimum: 'Three sips right now', normal: 'Drink a full glass', extra: 'Keep a bottle nearby all day', category: 'wellness' as const, durationMinutes: 2 },
  { title: 'Eat something', icon: '🍳', priority: 'must' as const, minimum: 'Grab a piece of fruit or crackers', normal: 'Eat a proper meal', category: 'wellness' as const, durationMinutes: 15 },
  { title: 'Shower', icon: '🚿', priority: 'must' as const, minimum: '2-minute warm rinse', normal: 'Full warm shower', extra: 'Wash hair if needed', category: 'wellness' as const, durationMinutes: 15 },
  // Should
  { title: 'Moisturize', icon: '🧴', priority: 'should' as const, minimum: 'Face only — 30 seconds', normal: 'Face and hands', extra: 'Full body after shower', category: 'wellness' as const, durationMinutes: 3 },
  { title: 'Move for 5 minutes', icon: '🚶', priority: 'should' as const, minimum: 'Stand up and walk to another room', normal: '5-minute gentle walk or stretch', extra: '20–30 minute walk', category: 'wellness' as const, durationMinutes: 5 },
  { title: 'Stretch', icon: '🧘', priority: 'should' as const, minimum: 'Roll shoulders and neck — 1 minute', normal: '5-minute full body stretch', category: 'wellness' as const, durationMinutes: 5 },
  { title: 'Lip care', icon: '🫦', priority: 'should' as const, minimum: 'Apply lip balm', normal: 'Apply lip balm and stay hydrated', category: 'wellness' as const, durationMinutes: 1 },
  { title: 'Change pillowcase', icon: '🛏️', priority: 'should' as const, minimum: 'At minimum, flip it', normal: 'Change to a fresh pillowcase', category: 'wellness' as const, durationMinutes: 3 },
  // Could
  { title: 'Hair care', icon: '💇', priority: 'could' as const, minimum: 'Comb or brush through', normal: 'Wash, condition, and style', category: 'wellness' as const, durationMinutes: 15 },
  { title: 'Nail care', icon: '💅', priority: 'could' as const, minimum: 'File one rough nail', normal: 'Clean and trim nails', category: 'wellness' as const, durationMinutes: 10 },
  { title: 'Skin care routine', icon: '✨', priority: 'could' as const, minimum: 'Moisturize and SPF', normal: 'Gentle cleanse, moisturize, SPF', category: 'wellness' as const, durationMinutes: 8 },
  { title: 'Longer walk', icon: '🏃', priority: 'could' as const, minimum: '10 minutes outside', normal: '20–30 minute walk', extra: '45+ minute walk', category: 'wellness' as const, durationMinutes: 30 },
  { title: 'Journal', icon: '📓', priority: 'could' as const, minimum: 'Write one sentence', normal: '5-minute reflection', category: 'wellness' as const, durationMinutes: 5 },
];

export const INITIAL_ROUTINES: Routine[] = [
  {
    id: 'routine-morning',
    title: 'Morning Awakening',
    icon: '🌅',
    description: 'Gentle low-pressure steps to transition into the day',
    enabled: true,
    timeOfDay: 'morning',
    steps: [
      { id: 'm1', title: 'Wake up and stretch arms', durationMinutes: 3, completed: true },
      { id: 'm2', title: 'Drink a tall glass of water', durationMinutes: 2, completed: true },
      { id: 'm3', title: 'Gentle warm shower', durationMinutes: 10, completed: true },
      { id: 'm4', title: 'Eat something simple', durationMinutes: 15, completed: false },
      { id: 'm5', title: 'Step outside or look at the sky', durationMinutes: 3, completed: false },
    ],
  },
  {
    id: 'routine-evening',
    title: 'Evening Wind-Down',
    icon: '🌙',
    description: 'Soft boundary between the day\'s effort and resting',
    enabled: true,
    timeOfDay: 'evening',
    steps: [
      { id: 'e1', title: 'Quiet warm dinner', durationMinutes: 25, completed: false },
      { id: 'e2', title: '5-minute micro room reset', durationMinutes: 5, completed: false },
      { id: 'e3', title: 'Dim bright overhead lights', durationMinutes: 1, completed: false },
      { id: 'e4', title: 'Put phone to charge across room', durationMinutes: 2, completed: false },
      { id: 'e5', title: 'Comfortable reading or audio', durationMinutes: 20, completed: false },
    ],
  },
  {
    id: 'routine-reset',
    title: 'Midday Cognitive Reset',
    icon: '🍃',
    description: 'When feeling scattered, step back to ground yourself',
    enabled: true,
    timeOfDay: 'afternoon',
    steps: [
      { id: 'r1', title: 'Stand up and roll shoulders back', durationMinutes: 2, completed: false },
      { id: 'r2', title: 'Drink cold water', durationMinutes: 1, completed: false },
      { id: 'r3', title: 'Close eyes for 5 slow breaths', durationMinutes: 2, completed: false },
      { id: 'r4', title: 'Choose just 1 tiny action next', durationMinutes: 1, completed: false },
    ],
  },
  // --- Wellness Routines ---
  {
    id: 'routine-morning-care',
    title: 'Morning Care',
    icon: '☀️',
    description: 'Simple self-care to start the day feeling a little more like yourself',
    enabled: true,
    timeOfDay: 'morning',
    category: 'wellness',
    steps: [
      { id: 'mc1', title: 'Brush teeth', durationMinutes: 2, completed: false },
      { id: 'mc2', title: 'Wash or rinse face', durationMinutes: 3, completed: false },
      { id: 'mc3', title: 'Moisturize', durationMinutes: 2, completed: false },
      { id: 'mc4', title: 'Lip balm', durationMinutes: 1, completed: false },
      { id: 'mc5', title: 'Drink a glass of water', durationMinutes: 2, completed: false },
      { id: 'mc6', title: 'SPF if going outside', durationMinutes: 1, completed: false },
      { id: 'mc7', title: 'Get dressed', durationMinutes: 5, completed: false },
      { id: 'mc8', title: '5-minute room reset (optional)', durationMinutes: 5, completed: false },
    ],
  },
  {
    id: 'routine-night-care',
    title: 'Night Care',
    icon: '🌙',
    description: 'End the day feeling clean and ready to actually rest',
    enabled: true,
    timeOfDay: 'evening',
    category: 'wellness',
    steps: [
      { id: 'nc1', title: 'Brush teeth', durationMinutes: 2, completed: false },
      { id: 'nc2', title: 'Wash face gently', durationMinutes: 3, completed: false },
      { id: 'nc3', title: 'Moisturize', durationMinutes: 2, completed: false },
      { id: 'nc4', title: 'Lip balm or petroleum jelly', durationMinutes: 1, completed: false },
      { id: 'nc5', title: 'Shower (if not done yet)', durationMinutes: 12, completed: false },
      { id: 'nc6', title: 'Prepare clothes for tomorrow', durationMinutes: 3, completed: false },
      { id: 'nc7', title: '5-minute journal (optional)', durationMinutes: 5, completed: false },
    ],
  },
  {
    id: 'routine-five-min-reset',
    title: '5-Minute Reset',
    icon: '💧',
    description: 'For very low-energy days. No pressure — this counts.',
    enabled: true,
    timeOfDay: 'anytime',
    category: 'wellness',
    steps: [
      { id: 'fr1', title: 'Drink water', durationMinutes: 1, completed: false },
      { id: 'fr2', title: 'Brush teeth', durationMinutes: 2, completed: false },
      { id: 'fr3', title: 'Wash or splash face', durationMinutes: 2, completed: false },
      { id: 'fr4', title: 'Change into clean clothes', durationMinutes: 3, completed: false },
      { id: 'fr5', title: 'Put away 3 things', durationMinutes: 2, completed: false },
    ],
  },
  {
    id: 'routine-event-prep',
    title: 'Event / Meeting Prep',
    icon: '🎯',
    description: 'Feel ready before something that matters. No scrambling.',
    enabled: true,
    timeOfDay: 'anytime',
    category: 'wellness',
    steps: [
      { id: 'ep1', title: 'Choose outfit and check it\'s clean', durationMinutes: 5, completed: false },
      { id: 'ep2', title: 'Hair and grooming', durationMinutes: 10, completed: false },
      { id: 'ep3', title: 'Shower if not already done', durationMinutes: 12, completed: false },
      { id: 'ep4', title: 'Skincare and lip balm', durationMinutes: 5, completed: false },
      { id: 'ep5', title: 'Brush teeth + deodorant', durationMinutes: 3, completed: false },
      { id: 'ep6', title: 'Check outfit in mirror', durationMinutes: 1, completed: false },
      { id: 'ep7', title: 'Charge phone and pack bag', durationMinutes: 5, completed: false },
      { id: 'ep8', title: 'Check transportation and time', durationMinutes: 3, completed: false },
      { id: 'ep9', title: 'Drink water before leaving', durationMinutes: 1, completed: false },
    ],
  },
];

// The 7-Day Fresh Start Template
export const FRESH_START_TEMPLATE = {
  id: 'tpl-fresh-start',
  name: '7-Day Fresh Start',
  goal: 'Look and feel cleaner, healthier, more rested, and comfortable. Not a weight-loss challenge. Just a week of basic care for yourself.',
  totalDays: 7,
  dailyMinimumTasks: [
    { title: 'Drink water', isOptional: false },
    { title: 'Eat normally', isOptional: false },
    { title: 'Brush teeth', isOptional: false },
    { title: 'Wash face', isOptional: false },
    { title: 'Moisturize', isOptional: false },
    { title: 'Lip care', isOptional: false },
    { title: 'Basic hygiene (deodorant)', isOptional: false },
    { title: '5–20 minutes of movement', isOptional: false },
    { title: 'Sleep routine (consistent bedtime)', isOptional: false },
  ],
  dailyOptionalTasks: [
    { title: 'Longer walk or workout', isOptional: true },
    { title: 'Hair care', isOptional: true },
    { title: 'Grooming (nails, facial hair)', isOptional: true },
    { title: 'Change pillowcase', isOptional: true },
    { title: '5-minute room reset', isOptional: true },
    { title: 'Journal', isOptional: true },
    { title: 'Outfit preparation for tomorrow', isOptional: true },
  ],
};

export const JOURNAL_PROMPTS_DAILY = [
  'How does my body feel today?',
  'What did I actually accomplish?',
  'What felt easier today?',
  'What was difficult?',
  'What do I need tomorrow?',
];

export const JOURNAL_PROMPTS_RESET = [
  'What changed today?',
  'Do I feel different from yesterday?',
  'What am I worried about?',
  'Is there anything I can actually do about it?',
  'What is one thing I did for myself today?',
];

export const INITIAL_RETURNS: ReturnDay[] = [
  { dayOfWeek: 'MON', dateStr: '2026-09-14', status: 'active', note: 'Did 2 minimums' },
  { dayOfWeek: 'TUE', dateStr: '2026-09-15', status: 'paused', note: 'Rest day — no pressure' },
  { dayOfWeek: 'WED', dateStr: '2026-09-16', status: 'paused', note: 'Quiet day off' },
  { dayOfWeek: 'THU', dateStr: '2026-09-17', status: 'returned', note: 'Returned with 1 small task' },
  { dayOfWeek: 'FRI', dateStr: '2026-09-18', status: 'active', note: 'Morning routine done' },
  { dayOfWeek: 'SAT', dateStr: '2026-09-19', status: 'active', note: 'Today in progress' },
  { dayOfWeek: 'SUN', dateStr: '2026-09-20', status: 'paused', note: 'Planned reset' },
];

export const INITIAL_HELPFUL_INSIGHTS: HelpfulInsight[] = [
  { id: 'h1', label: '2-minute mini starts', icon: '⏱', count: 9 },
  { id: 'h2', label: 'Someone nearby / body double', icon: '👥', count: 6 },
  { id: 'h3', label: 'Noise reduction / headphones', icon: '🎧', count: 5 },
  { id: 'h4', label: 'Intentional quiet rest first', icon: '☕', count: 4 },
  { id: 'h5', label: 'Breaking task into 1 tiny step', icon: '🧩', count: 7 },
];

export const INITIAL_RESETS: Reset[] = [];

export const INITIAL_JOURNAL_ENTRIES: WellnessJournalEntry[] = [];

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'light',
  defaultTimerMinutes: 2,
  soundEnabled: true,
  reducedMotion: false,
  hapticFeedback: true,
  wellnessEnabled: true,
  hasCompletedOnboarding: false,
  startingDifficulty: 'gentle',
  showExtras: false,
  onboardingGoals: [],
};
