import { Task, Routine, ReturnDay, HelpfulInsight, UserSettings } from '../types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Work on project',
    category: 'productive',
    icon: '💻',
    timeCategory: 'now',
    scheduledTime: undefined,
    durationMinutes: 25,
    priority: 'must',
    minimum: 'Open laptop and open the file',
    normal: 'Work focused for 25 minutes',
    extra: 'Review and commit current changes',
    steps: [
      { id: 's1', title: 'Sit down at the workspace', completed: true },
      { id: 's2', title: 'Open laptop lid', completed: false, isMinimum: true },
      { id: 's3', title: 'Open the project file', completed: false },
      { id: 's4', title: 'Review the last line edited', completed: false },
      { id: 's5', title: 'Make one small edit or test run', completed: false },
    ],
    companyPreference: 'someone_nearby',
    completed: false,
    orderIndex: 0,
  },
  {
    id: 'task-2',
    title: 'Listen to quiet music & breathe',
    category: 'rest',
    icon: '☕',
    timeCategory: 'today',
    scheduledTime: '15:30',
    durationMinutes: 15,
    priority: 'should',
    minimum: 'Sit with eyes closed for 2 minutes',
    normal: 'Enjoy 15 minutes of calm audio',
    extra: 'Make a warm cup of herbal tea',
    steps: [
      { id: 'r1', title: 'Put on headphones', completed: false },
      { id: 'r2', title: 'Press play on ambient playlist', completed: false },
      { id: 'r3', title: 'Rest head back and exhale', completed: false },
    ],
    companyPreference: 'alone',
    completed: false,
    orderIndex: 1,
  },
  {
    id: 'task-3',
    title: 'Eat a proper lunch',
    category: 'wellness',
    icon: '🍳',
    timeCategory: 'today',
    scheduledTime: '13:00',
    durationMinutes: 20,
    priority: 'must',
    minimum: 'Grab a piece of fruit or toast',
    normal: 'Sit down with a warm meal',
    extra: 'Drink a full tall glass of water',
    steps: [
      { id: 'l1', title: 'Walk to the kitchen', completed: false },
      { id: 'l2', title: 'Get food onto a plate', completed: false },
      { id: 'l3', title: 'Eat without rushing', completed: false },
    ],
    companyPreference: 'no_preference',
    completed: false,
    orderIndex: 2,
  },
  {
    id: 'task-4',
    title: 'Reset desk surface',
    category: 'routine',
    icon: '🧹',
    timeCategory: 'later',
    durationMinutes: 10,
    priority: 'could',
    minimum: 'Put 1 empty cup in the kitchen sink',
    normal: 'Throw away wrappers & tuck papers',
    extra: 'Wipe surface with a damp cloth',
    steps: [
      { id: 'd1', title: 'Take cups to sink', completed: false },
      { id: 'd2', title: 'Throw scrap paper away', completed: false },
      { id: 'd3', title: 'Line up keyboard and mouse', completed: false },
    ],
    companyPreference: 'background_company',
    completed: false,
    orderIndex: 3,
  },
  {
    id: 'task-5',
    title: 'Shower & get dressed',
    category: 'wellness',
    icon: '🚿',
    timeCategory: 'today',
    scheduledTime: '09:00',
    durationMinutes: 15,
    priority: 'must',
    minimum: '2-minute warm rinse',
    normal: 'Full warm shower',
    steps: [
      { id: 'sh1', title: 'Turn water on warm', completed: true },
      { id: 'sh2', title: 'Step in for rinse', completed: true },
    ],
    companyPreference: 'alone',
    completed: true,
    completedAt: '2026-09-19T09:18:00',
    completedTier: 'minimum',
    orderIndex: 4,
  },
  {
    id: 'task-6',
    title: 'Morning glass of water',
    category: 'wellness',
    icon: '💧',
    timeCategory: 'today',
    durationMinutes: 2,
    priority: 'should',
    minimum: 'Take three sips',
    normal: 'Drink full glass',
    steps: [
      { id: 'w1', title: 'Fill glass', completed: true },
      { id: 'w2', title: 'Drink slowly', completed: true },
    ],
    companyPreference: 'no_preference',
    completed: true,
    completedAt: '2026-09-19T08:30:00',
    completedTier: 'normal',
    orderIndex: 5,
  },
];

export const INITIAL_ROUTINES: Routine[] = [
  {
    id: 'routine-morning',
    title: 'Morning Awakening',
    icon: '🌅',
    description: 'Gentle low-pressure steps to transition into the day',
    enabled: true,
    timeOfDay: 'morning',
    steps: [
      { id: 'm1', title: 'Wake up and stretch arms', durationMinutes: 3, completed: true },
      { id: 'm2', title: 'Drink a tall glass of water', durationMinutes: 2, completed: true },
      { id: 'm3', title: 'Gentle warm shower', durationMinutes: 10, completed: true },
      { id: 'm4', title: 'Eat something simple', durationMinutes: 15, completed: false },
      { id: 'm5', title: 'Step outside or look at the sky', durationMinutes: 3, completed: false },
    ],
  },
  {
    id: 'routine-evening',
    title: 'Evening Wind-Down',
    icon: '🌙',
    description: 'Soft boundary between the day’s effort and resting',
    enabled: true,
    timeOfDay: 'evening',
    steps: [
      { id: 'e1', title: 'Quiet warm dinner', durationMinutes: 25, completed: false },
      { id: 'e2', title: '5-minute micro room reset', durationMinutes: 5, completed: false },
      { id: 'e3', title: 'Dim bright overhead lights', durationMinutes: 1, completed: false },
      { id: 'e4', title: 'Put phone to charge across room', durationMinutes: 2, completed: false },
      { id: 'e5', title: 'Comfortable reading or audio', durationMinutes: 20, completed: false },
    ],
  },
  {
    id: 'routine-reset',
    title: 'Midday Cognitive Reset',
    icon: '🍃',
    description: 'When feeling scattered, step back to ground yourself',
    enabled: true,
    timeOfDay: 'afternoon',
    steps: [
      { id: 'r1', title: 'Stand up and roll shoulders back', durationMinutes: 2, completed: false },
      { id: 'r2', title: 'Drink cold water', durationMinutes: 1, completed: false },
      { id: 'r3', title: 'Close eyes for 5 slow breaths', durationMinutes: 2, completed: false },
      { id: 'r4', title: 'Choose just 1 tiny action next', durationMinutes: 1, completed: false },
    ],
  }
];

export const INITIAL_RETURNS: ReturnDay[] = [
  { dayOfWeek: 'MON', dateStr: '2026-09-14', status: 'active', note: 'Did 2 minimums' },
  { dayOfWeek: 'TUE', dateStr: '2026-09-15', status: 'paused', note: 'Rest day — no pressure' },
  { dayOfWeek: 'WED', dateStr: '2026-09-16', status: 'paused', note: 'Quiet day off' },
  { dayOfWeek: 'THU', dateStr: '2026-09-17', status: 'returned', note: 'Returned with 1 small task' },
  { dayOfWeek: 'FRI', dateStr: '2026-09-18', status: 'active', note: 'Morning routine done' },
  { dayOfWeek: 'SAT', dateStr: '2026-09-19', status: 'active', note: 'Today in progress' },
  { dayOfWeek: 'SUN', dateStr: '2026-09-20', status: 'paused', note: 'Planned reset' },
];

export const INITIAL_HELPFUL_INSIGHTS: HelpfulInsight[] = [
  { id: 'h1', label: '2-minute mini starts', icon: '⏱', count: 9 },
  { id: 'h2', label: 'Someone nearby / body double', icon: '👥', count: 6 },
  { id: 'h3', label: 'Noise reduction / headphones', icon: '🎧', count: 5 },
  { id: 'h4', label: 'Intentional quiet rest first', icon: '☕', count: 4 },
  { id: 'h5', label: 'Breaking task into 1 tiny step', icon: '🧩', count: 7 },
];

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'light',
  defaultTimerMinutes: 2,
  soundEnabled: true,
  reducedMotion: false,
  hapticFeedback: true,
};
